bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: ZojtB07AxpuXa+1mFbwlVmeQYBQLEgtpXG6zFbZcm4m8UBOcTZBgmoBRoHonzXKsEbjRXCzRa/357GlBQD58IlEoQDf/XNSjbLdj+Iw/Y7BvVbvRjvQvrEodH+QPWMkyKIE9ZYmJR4tU+cChX5X56lTHvL+dvwT9tRD0bhoGjiyQekZeBjVJ37qW0Nap+uPBqMWCi86qkdqtTXtX5E71zHDS2jVGwM9yu8a/DmRTgA41idBQJ13Ue7DJOpCeNgWNFnMCDYE02fZZke5V+XClwITSiI+j9LRzIVLno6ekOAuqw+b3dDBlry7DlfmXAiVW16MzD9wXKtzbsmeeyFLwxFjAnZ0r1lVi5NNFvTgO2hBBEeLH6JTzKoi5rT2zPcFR2fGsEpGRU385oc0LuDzRg6mVYHgyqDFzeKjAVNWz/nehW3ABm8aQJCSZRbttVo7b9owTWj+GPkjiLYF6G70gYNZhZIWhuU6tsbrqAexmNxrsKCoE9rcMT/CWyFvdsd8e4HRXEk+QxQuLww4Aj86mhkRgHswxapTiSkPw6VJtq4zSSIiSwskv4Uol+mgIxUmdq4sonVSKYqTzDeLu4P5f3Ks0m0wEjdkgqigxZOW2o5CXzLhXHBXYNbrdHZ1w2A+Ze4CCHBkTWGn1b18f/rnnD9z7Ru9iqqvo0uyqQvSstrA=
conda_forge_output_validation: true
